#pragma once

#define MAX_DESCRIPTORS_PER_SET 8
#define MAX_ENABLED_EXTENSIONS 8
#define MAX_ENABLED_LAYERS 8
#define MAX_DESCRIPTOR_SETS 8192
#define MAX_UNIFORM_BUFFER_DESCRIPTORS 8192
#define MAX_STORAGE_BUFFER_DESCRIPTORS 32
#define MAX_STORAGE_IMAGE_DESCRIPTORS 32
#define MAX_SAMPLER_DESCRIPTORS 16384
#define MAX_BOUND_DESCRIPTOR_SETS 4

#define SELECTED_COMP_COLOR glm::vec4(1.0f, 1.0f, 0.5f, 1.0f)
#define MULTI_SELECTED_COMP_COLOR glm::vec4(1.0f, 0.6f, 0.3f, 1.0f)

#define PATH_TRACE_MAX_TRIANGLES 500000
#define PATH_TRACE_MAX_MESHES 4096
#define PATH_TRACE_MAX_LIGHTS 1024
#define PATH_TRACE_MAX_TEXTURES 1024
