#pragma once

#include "Input/InputConstants.h"

#include <vector>
#include <stdint.h>

#if PLATFORM_WINDOWS
#include <windows.h>
#include <Xinput.h>
#elif PLATFORM_DOLPHIN
#include <gccore.h>
#elif PLATFORM_3DS
#include <3ds.h>
#endif

class Signal;

enum class GamepadType
{
    Standard,
    GameCube,
    Wiimote,
    WiiClassic,

    Count
};

enum MouseCode
{
    MOUSE_LEFT,
    MOUSE_RIGHT,
    MOUSE_MIDDLE,
    MOUSE_X1,
    MOUSE_X2,

    MOUSE_BUTTON_COUNT
};

enum GamepadButtonCode
{
    GAMEPAD_A,
    GAMEPAD_B,
    GAMEPAD_C,
    GAMEPAD_X,
    GAMEPAD_Y,
    GAMEPAD_Z,
    GAMEPAD_L1,
    GAMEPAD_R1,
    GAMEPAD_L2,
    GAMEPAD_R2,
    GAMEPAD_THUMBL,
    GAMEPAD_THUMBR,
    GAMEPAD_START,
    GAMEPAD_SELECT,
    GAMEPAD_LEFT,
    GAMEPAD_RIGHT,
    GAMEPAD_UP,
    GAMEPAD_DOWN,
    GAMEPAD_L_LEFT,
    GAMEPAD_L_RIGHT,
    GAMEPAD_L_UP,
    GAMEPAD_L_DOWN,
    GAMEPAD_R_LEFT,
    GAMEPAD_R_RIGHT,
    GAMEPAD_R_UP,
    GAMEPAD_R_DOWN,
    GAMEPAD_HOME,

    GAMEPAD_BUTTON_COUNT
};

enum GamepadAxisCode
{
    GAMEPAD_AXIS_LTRIGGER,
    GAMEPAD_AXIS_RTRIGGER,
    GAMEPAD_AXIS_LTHUMB_X,
    GAMEPAD_AXIS_LTHUMB_Y,
    GAMEPAD_AXIS_RTHUMB_X,
    GAMEPAD_AXIS_RTHUMB_Y,

    GAMEPAD_AXIS_COUNT
};

struct GamepadState
{
    int32_t mDevice = -1;
    int32_t mButtons[GAMEPAD_BUTTON_COUNT] = { };
    float mAxes[GAMEPAD_AXIS_COUNT] = { };
    float mAccel[3] = { }; // x, y, z accelerometer values
    float mGyro[3] = { };  // x, y, z gyroscope values
    float mOrientation[3] = { };  // pitch, yaw, roll in degrees
    GamepadType mType = GamepadType::Standard;
    bool mConnected = false;
};

struct InputState
{
    bool mKeys[INPUT_MAX_KEYS] = { };
    bool mMouseButtons[MOUSE_BUTTON_COUNT] = { };
    bool mTouches[INPUT_MAX_TOUCHES] = { };
    GamepadState mGamepads[INPUT_MAX_GAMEPADS];

    bool mPrevKeys[INPUT_MAX_KEYS] = { };
    bool mPrevMouseButtons[MOUSE_BUTTON_COUNT] = { };
    bool mPrevTouches[INPUT_MAX_TOUCHES] = { };
    GamepadState mPrevGamepads[INPUT_MAX_GAMEPADS];

    bool mRepeatKeys[INPUT_MAX_KEYS] = { };
    int32_t mScrollWheelDelta = 0;
    int32_t mMouseDeltaX = 0;
    int32_t mMouseDeltaY = 0;

    int32_t mPointerX[INPUT_MAX_TOUCHES] = { 0 };
    int32_t mPointerY[INPUT_MAX_TOUCHES] = { 0 };
    int32_t mNumControllers = 0;

    std::vector<int32_t> mJustDownKeys;

    bool mCursorLocked = false;
    bool mCursorTrapped = false;
    bool mCursorShown = true;

#if PLATFORM_WINDOWS
    XINPUT_STATE mXinputStates[INPUT_MAX_GAMEPADS] = { };
    XINPUT_STATE mXinputPrevStates[INPUT_MAX_GAMEPADS] = { };
    bool mActiveControllers[INPUT_MAX_GAMEPADS] = { };
#endif
};

#if PLATFORM_WINDOWS

enum KeyCode
{
    OCTAVE_KEY_BACK = 10,
    OCTAVE_KEY_ESCAPE = 27,

    OCTAVE_KEY_0 = 48,
    OCTAVE_KEY_1 = 49,
    OCTAVE_KEY_2 = 50,
    OCTAVE_KEY_3 = 51,
    OCTAVE_KEY_4 = 52,
    OCTAVE_KEY_5 = 53,
    OCTAVE_KEY_6 = 54,
    OCTAVE_KEY_7 = 55,
    OCTAVE_KEY_8 = 56,
    OCTAVE_KEY_9 = 57,

    OCTAVE_KEY_A = 65,
    OCTAVE_KEY_B = 66,
    OCTAVE_KEY_C = 67,
    OCTAVE_KEY_D = 68,
    OCTAVE_KEY_E = 69,
    OCTAVE_KEY_F = 70,
    OCTAVE_KEY_G = 71,
    OCTAVE_KEY_H = 72,
    OCTAVE_KEY_I = 73,
    OCTAVE_KEY_J = 74,
    OCTAVE_KEY_K = 75,
    OCTAVE_KEY_L = 76,
    OCTAVE_KEY_M = 77,
    OCTAVE_KEY_N = 78,
    OCTAVE_KEY_O = 79,
    OCTAVE_KEY_P = 80,
    OCTAVE_KEY_Q = 81,
    OCTAVE_KEY_R = 82,
    OCTAVE_KEY_S = 83,
    OCTAVE_KEY_T = 84,
    OCTAVE_KEY_U = 85,
    OCTAVE_KEY_V = 86,
    OCTAVE_KEY_W = 87,
    OCTAVE_KEY_X = 88,
    OCTAVE_KEY_Y = 89,
    OCTAVE_KEY_Z = 90,

    OCTAVE_KEY_SPACE = 32,
    OCTAVE_KEY_ENTER = 13,
    OCTAVE_KEY_BACKSPACE = 8,
    OCTAVE_KEY_TAB = 9,

    OCTAVE_KEY_SHIFT_L = 16,
    OCTAVE_KEY_CONTROL_L = 17,
    OCTAVE_KEY_ALT_L = 18,
    OCTAVE_KEY_SHIFT_R = 16,
    OCTAVE_KEY_CONTROL_R = 17,
    OCTAVE_KEY_ALT_R = 18,

    OCTAVE_KEY_INSERT = 0x2D,
    OCTAVE_KEY_DELETE = 0x2E,
    OCTAVE_KEY_HOME = 0x24,
    OCTAVE_KEY_END = 0x23,
    OCTAVE_KEY_PAGE_UP = 33,
    OCTAVE_KEY_PAGE_DOWN = 34,

    OCTAVE_KEY_UP = 38,
    OCTAVE_KEY_DOWN = 40,
    OCTAVE_KEY_LEFT = 37,
    OCTAVE_KEY_RIGHT = 39,

    OCTAVE_KEY_NUMPAD0 = 96,
    OCTAVE_KEY_NUMPAD1 = 97,
    OCTAVE_KEY_NUMPAD2 = 98,
    OCTAVE_KEY_NUMPAD3 = 99,
    OCTAVE_KEY_NUMPAD4 = 100,
    OCTAVE_KEY_NUMPAD5 = 101,
    OCTAVE_KEY_NUMPAD6 = 102,
    OCTAVE_KEY_NUMPAD7 = 103,
    OCTAVE_KEY_NUMPAD8 = 104,
    OCTAVE_KEY_NUMPAD9 = 105,

    OCTAVE_KEY_F1 = 112,
    OCTAVE_KEY_F2 = 113,
    OCTAVE_KEY_F3 = 114,
    OCTAVE_KEY_F4 = 115,
    OCTAVE_KEY_F5 = 116,
    OCTAVE_KEY_F6 = 117,
    OCTAVE_KEY_F7 = 118,
    OCTAVE_KEY_F8 = 119,
    OCTAVE_KEY_F9 = 120,
    OCTAVE_KEY_F10 = 121,
    OCTAVE_KEY_F11 = 122,
    OCTAVE_KEY_F12 = 123,

    OCTAVE_KEY_PERIOD = 0xBE,
    OCTAVE_KEY_COMMA = 0xBC,
    OCTAVE_KEY_PLUS = 0xBB,
    OCTAVE_KEY_MINUS = 0xBD,

    OCTAVE_KEY_COLON = 0xBA,
    OCTAVE_KEY_QUESTION = 0xBF,
    OCTAVE_KEY_SQUIGGLE = 0xC0,
    OCTAVE_KEY_LEFT_BRACKET = 0xDB,
    OCTAVE_KEY_BACK_SLASH = 0xDC,
    OCTAVE_KEY_RIGHT_BRACKET = 0xDD,
    OCTAVE_KEY_QUOTE = 0xDE,

    OCTAVE_KEY_DECIMAL = 0x6E
};

#elif PLATFORM_ANDROID

enum KeyCode
{
    OCTAVE_KEY_BACK = 4,
    OCTAVE_KEY_ESCAPE = 255,

    OCTAVE_KEY_0 = 7,
    OCTAVE_KEY_1 = 8,
    OCTAVE_KEY_2 = 9,
    OCTAVE_KEY_3 = 10,
    OCTAVE_KEY_4 = 11,
    OCTAVE_KEY_5 = 12,
    OCTAVE_KEY_6 = 13,
    OCTAVE_KEY_7 = 14,
    OCTAVE_KEY_8 = 15,
    OCTAVE_KEY_9 = 16,

    OCTAVE_KEY_A = 29,
    OCTAVE_KEY_B = 30,
    OCTAVE_KEY_C = 31,
    OCTAVE_KEY_D = 32,
    OCTAVE_KEY_E = 33,
    OCTAVE_KEY_F = 34,
    OCTAVE_KEY_G = 35,
    OCTAVE_KEY_H = 36,
    OCTAVE_KEY_I = 37,
    OCTAVE_KEY_J = 38,
    OCTAVE_KEY_K = 39,
    OCTAVE_KEY_L = 40,
    OCTAVE_KEY_M = 41,
    OCTAVE_KEY_N = 42,
    OCTAVE_KEY_O = 43,
    OCTAVE_KEY_P = 44,
    OCTAVE_KEY_Q = 45,
    OCTAVE_KEY_R = 46,
    OCTAVE_KEY_S = 47,
    OCTAVE_KEY_T = 48,
    OCTAVE_KEY_U = 49,
    OCTAVE_KEY_V = 50,
    OCTAVE_KEY_W = 51,
    OCTAVE_KEY_X = 52,
    OCTAVE_KEY_Y = 53,
    OCTAVE_KEY_Z = 54,

    OCTAVE_KEY_SPACE = 62,
    OCTAVE_KEY_ENTER = 66,
    OCTAVE_KEY_BACKSPACE = 67,
    OCTAVE_KEY_TAB = 61,

    OCTAVE_KEY_SHIFT_L = 60,
    OCTAVE_KEY_CONTROL_L = 113,
    OCTAVE_KEY_ALT_L = 255,
    OCTAVE_KEY_SHIFT_R = 60,
    OCTAVE_KEY_CONTROL_R = 113,
    OCTAVE_KEY_ALT_R = 255,

    OCTAVE_KEY_UP = 19,
    OCTAVE_KEY_DOWN = 20,
    OCTAVE_KEY_LEFT = 21,
    OCTAVE_KEY_RIGHT = 22,

    OCTAVE_KEY_NUMPAD0 = 144,
    OCTAVE_KEY_NUMPAD1 = 145,
    OCTAVE_KEY_NUMPAD2 = 146,
    OCTAVE_KEY_NUMPAD3 = 147,
    OCTAVE_KEY_NUMPAD4 = 148,
    OCTAVE_KEY_NUMPAD5 = 149,
    OCTAVE_KEY_NUMPAD6 = 150,
    OCTAVE_KEY_NUMPAD7 = 151,
    OCTAVE_KEY_NUMPAD8 = 152,
    OCTAVE_KEY_NUMPAD9 = 153,

    OCTAVE_KEY_F1 = 131,
    OCTAVE_KEY_F2 = 132,
    OCTAVE_KEY_F3 = 133,
    OCTAVE_KEY_F4 = 134,
    OCTAVE_KEY_F5 = 135,
    OCTAVE_KEY_F6 = 136,
    OCTAVE_KEY_F7 = 137,
    OCTAVE_KEY_F8 = 138,
    OCTAVE_KEY_F9 = 139,
    OCTAVE_KEY_F10 = 140,
    OCTAVE_KEY_F11 = 141,
    OCTAVE_KEY_F12 = 142,

    OCTAVE_KEY_PERIOD = 56,
    OCTAVE_KEY_COMMA = 55,
    OCTAVE_KEY_PLUS = 70,
    OCTAVE_KEY_MINUS = 69,
    OCTAVE_KEY_COLON = 74,
    OCTAVE_KEY_QUESTION = 76,
    OCTAVE_KEY_SQUIGGLE = 216, // Couldnt find keycode
    OCTAVE_KEY_LEFT_BRACKET = 71,
    OCTAVE_KEY_BACK_SLASH = 73,
    OCTAVE_KEY_RIGHT_BRACKET = 72,
    OCTAVE_KEY_QUOTE = 218, // Couldnt find keycode

    OCTAVE_KEY_INSERT = 255,
    OCTAVE_KEY_DELETE = 67,
    OCTAVE_KEY_HOME = 255,
    OCTAVE_KEY_END = 255,
    OCTAVE_KEY_PAGE_UP = 255,
    OCTAVE_KEY_PAGE_DOWN = 255,

    OCTAVE_KEY_DECIMAL = 255 //???
};

// TODO: Use these button values in INP_Update()

/*
TODO: ANDROID-PLAT - These enum names conflict with the GamepadButtonCode enum above.
enum GamepadCode
{
    GAMEPAD_A = 96,
    GAMEPAD_B = 97,
    GAMEPAD_C = 98,
    GAMEPAD_X = 99,
    GAMEPAD_Y = 100,
    GAMEPAD_Z = 101,
    GAMEPAD_L1 = 102,
    GAMEPAD_R1 = 103,
    GAMEPAD_L2 = 104,
    GAMEPAD_R2 = 105,
    GAMEPAD_THUMBL = 106,
    GAMEPAD_THUMBR = 107,
    GAMEPAD_START = 108,
    GAMEPAD_SELECT = 109,
    GAMEPAD_LEFT = 0,
    GAMEPAD_RIGHT = 0,
    GAMEPAD_UP = 0,
    GAMEPAD_DOWN = 0,

    GAMEPAD_AXIS_X = 0,
    GAMEPAD_AXIS_Y = 1,
    GAMEPAD_AXIS_Z = 11,
    GAMEPAD_AXIS_RZ = 14,
    GAMEPAD_AXIS_HAT_X = 15,
    GAMEPAD_AXIS_HAT_Y = 16,
    GAMEPAD_AXIS_LTRIGGER = 17,
    GAMEPAD_AXIS_RTRIGGER = 18
};
*/

#elif PLATFORM_3DS

// 3DS has conflicts with OCTAVE_KEY_A, OCTAVE_KEY_B, OCTAVE_KEY_L, OCTAVE_KEY_DOWN, etc
// because it uses those names for the gamepad buttons.
// For now this version of the enum omits those

enum KeyCode
{
    OCTAVE_KEY_BACK = 10,
    OCTAVE_KEY_ESCAPE = 255,

    OCTAVE_KEY_0 = 48,
    OCTAVE_KEY_1 = 49,
    OCTAVE_KEY_2 = 50,
    OCTAVE_KEY_3 = 51,
    OCTAVE_KEY_4 = 52,
    OCTAVE_KEY_5 = 53,
    OCTAVE_KEY_6 = 54,
    OCTAVE_KEY_7 = 55,
    OCTAVE_KEY_8 = 56,
    OCTAVE_KEY_9 = 57,

    //OCTAVE_KEY_A = 65,
    //OCTAVE_KEY_B = 66,
    OCTAVE_KEY_C = 67,
    OCTAVE_KEY_D = 68,
    OCTAVE_KEY_E = 69,
    OCTAVE_KEY_F = 70,
    OCTAVE_KEY_G = 71,
    OCTAVE_KEY_H = 72,
    OCTAVE_KEY_I = 73,
    OCTAVE_KEY_J = 74,
    OCTAVE_KEY_K = 75,
    //OCTAVE_KEY_L = 76,
    OCTAVE_KEY_M = 77,
    OCTAVE_KEY_N = 78,
    OCTAVE_KEY_O = 79,
    OCTAVE_KEY_P = 80,
    OCTAVE_KEY_Q = 81,
    //OCTAVE_KEY_R = 82,
    OCTAVE_KEY_S = 83,
    OCTAVE_KEY_T = 84,
    OCTAVE_KEY_U = 85,
    OCTAVE_KEY_V = 86,
    OCTAVE_KEY_W = 87,
    //OCTAVE_KEY_X = 88,
    //OCTAVE_KEY_Y = 89,
    OCTAVE_KEY_Z = 90,

    OCTAVE_KEY_SPACE = 32,
    OCTAVE_KEY_ENTER = 13,
    OCTAVE_KEY_BACKSPACE = 8,
    OCTAVE_KEY_TAB = 9,

    OCTAVE_KEY_SHIFT_L = 16,
    OCTAVE_KEY_CONTROL_L = 17,
    OCTAVE_KEY_ALT_L = 255,
    OCTAVE_KEY_SHIFT_R = 16,
    OCTAVE_KEY_CONTROL_R = 17,
    OCTAVE_KEY_ALT_R = 255,

    OCTAVE_KEY_INSERT = 255,
    OCTAVE_KEY_DELETE = 255,
    OCTAVE_KEY_HOME = 255,
    OCTAVE_KEY_END = 255,
    OCTAVE_KEY_PAGE_UP = 33,
    OCTAVE_KEY_PAGE_DOWN = 34,

    //OCTAVE_KEY_UP = 38,
    //OCTAVE_KEY_DOWN = 40,
    //OCTAVE_KEY_LEFT = 37,
    //OCTAVE_KEY_RIGHT = 39,

    OCTAVE_KEY_NUMPAD0 = 96,
    OCTAVE_KEY_NUMPAD1 = 97,
    OCTAVE_KEY_NUMPAD2 = 98,
    OCTAVE_KEY_NUMPAD3 = 99,
    OCTAVE_KEY_NUMPAD4 = 100,
    OCTAVE_KEY_NUMPAD5 = 101,
    OCTAVE_KEY_NUMPAD6 = 102,
    OCTAVE_KEY_NUMPAD7 = 103,
    OCTAVE_KEY_NUMPAD8 = 104,
    OCTAVE_KEY_NUMPAD9 = 105,

    OCTAVE_KEY_F1 = 112,
    OCTAVE_KEY_F2 = 113,
    OCTAVE_KEY_F3 = 114,
    OCTAVE_KEY_F4 = 115,
    OCTAVE_KEY_F5 = 116,
    OCTAVE_KEY_F6 = 117,
    OCTAVE_KEY_F7 = 118,
    OCTAVE_KEY_F8 = 119,
    OCTAVE_KEY_F9 = 120,
    OCTAVE_KEY_F10 = 121,
    OCTAVE_KEY_F11 = 122,
    OCTAVE_KEY_F12 = 123,

    OCTAVE_KEY_PERIOD = 0xBE,
    OCTAVE_KEY_COMMA = 0xBC,
    OCTAVE_KEY_PLUS = 0xBB,
    OCTAVE_KEY_MINUS = 0xBD,

    OCTAVE_KEY_COLON = 0xBA,
    OCTAVE_KEY_QUESTION = 0xBF,
    OCTAVE_KEY_SQUIGGLE = 0xC0,
    OCTAVE_KEY_LEFT_BRACKET = 0xDB,
    OCTAVE_KEY_BACK_SLASH = 0xDC,
    OCTAVE_KEY_RIGHT_BRACKET = 0xDD,
    OCTAVE_KEY_QUOTE = 0xDE,

    OCTAVE_KEY_DECIMAL = 0x6E
};

#elif PLATFORM_LINUX

enum KeyCode
{
    OCTAVE_KEY_BACK = 22,
    OCTAVE_KEY_ESCAPE = 9,

    OCTAVE_KEY_0 = 19,
    OCTAVE_KEY_1 = 10,
    OCTAVE_KEY_2 = 11,
    OCTAVE_KEY_3 = 12,
    OCTAVE_KEY_4 = 13,
    OCTAVE_KEY_5 = 14,
    OCTAVE_KEY_6 = 15,
    OCTAVE_KEY_7 = 16,
    OCTAVE_KEY_8 = 17,
    OCTAVE_KEY_9 = 18,

    OCTAVE_KEY_A = 38,
    OCTAVE_KEY_B = 56,
    OCTAVE_KEY_C = 54,
    OCTAVE_KEY_D = 40,
    OCTAVE_KEY_E = 26,
    OCTAVE_KEY_F = 41,
    OCTAVE_KEY_G = 42,
    OCTAVE_KEY_H = 43,
    OCTAVE_KEY_I = 31,
    OCTAVE_KEY_J = 44,
    OCTAVE_KEY_K = 45,
    OCTAVE_KEY_L = 46,
    OCTAVE_KEY_M = 58,
    OCTAVE_KEY_N = 57,
    OCTAVE_KEY_O = 32,
    OCTAVE_KEY_P = 33,
    OCTAVE_KEY_Q = 24,
    OCTAVE_KEY_R = 27,
    OCTAVE_KEY_S = 39,
    OCTAVE_KEY_T = 28,
    OCTAVE_KEY_U = 30,
    OCTAVE_KEY_V = 55,
    OCTAVE_KEY_W = 25,
    OCTAVE_KEY_X = 53,
    OCTAVE_KEY_Y = 29,
    OCTAVE_KEY_Z = 52,

    OCTAVE_KEY_SPACE = 65,
    OCTAVE_KEY_ENTER = 36,
    OCTAVE_KEY_BACKSPACE = 22,
    OCTAVE_KEY_TAB = 23,

    OCTAVE_KEY_SHIFT_L = 50,
    OCTAVE_KEY_CONTROL_L = 37,
    OCTAVE_KEY_ALT_L = 64,
    OCTAVE_KEY_SHIFT_R = 62,
    OCTAVE_KEY_CONTROL_R = 105,
    OCTAVE_KEY_ALT_R = 108,

    OCTAVE_KEY_INSERT = 118,
    OCTAVE_KEY_DELETE = 119,
    OCTAVE_KEY_HOME = 110,
    OCTAVE_KEY_END = 115,
    OCTAVE_KEY_PAGE_UP = 112,
    OCTAVE_KEY_PAGE_DOWN = 117,

    OCTAVE_KEY_UP = 111,
    OCTAVE_KEY_DOWN = 116,
    OCTAVE_KEY_LEFT = 113,
    OCTAVE_KEY_RIGHT = 114,

    OCTAVE_KEY_NUMPAD0 = 90,
    OCTAVE_KEY_NUMPAD1 = 87,
    OCTAVE_KEY_NUMPAD2 = 88,
    OCTAVE_KEY_NUMPAD3 = 89,
    OCTAVE_KEY_NUMPAD4 = 83,
    OCTAVE_KEY_NUMPAD5 = 84,
    OCTAVE_KEY_NUMPAD6 = 85,
    OCTAVE_KEY_NUMPAD7 = 79,
    OCTAVE_KEY_NUMPAD8 = 80,
    OCTAVE_KEY_NUMPAD9 = 81,

    OCTAVE_KEY_F1 = 67,
    OCTAVE_KEY_F2 = 68,
    OCTAVE_KEY_F3 = 69,
    OCTAVE_KEY_F4 = 70,
    OCTAVE_KEY_F5 = 71,
    OCTAVE_KEY_F6 = 72,
    OCTAVE_KEY_F7 = 73,
    OCTAVE_KEY_F8 = 74,
    OCTAVE_KEY_F9 = 75,
    OCTAVE_KEY_F10 = 76,
    OCTAVE_KEY_F11 = 95,
    OCTAVE_KEY_F12 = 96,

    OCTAVE_KEY_PERIOD = 60,
    OCTAVE_KEY_COMMA = 59,
    OCTAVE_KEY_PLUS = 21,
    OCTAVE_KEY_MINUS = 20,

    OCTAVE_KEY_COLON = 47,
    OCTAVE_KEY_QUESTION = 61,
    OCTAVE_KEY_SQUIGGLE = 49,
    OCTAVE_KEY_LEFT_BRACKET = 34,
    OCTAVE_KEY_BACK_SLASH = 51,
    OCTAVE_KEY_RIGHT_BRACKET = 35,
    OCTAVE_KEY_QUOTE = 48,

    OCTAVE_KEY_DECIMAL = 91
};

#else // All other platforms

enum KeyCode
{
    OCTAVE_KEY_BACK = 10,
    OCTAVE_KEY_ESCAPE = 27,

    OCTAVE_KEY_0 = 48,
    OCTAVE_KEY_1 = 49,
    OCTAVE_KEY_2 = 50,
    OCTAVE_KEY_3 = 51,
    OCTAVE_KEY_4 = 52,
    OCTAVE_KEY_5 = 53,
    OCTAVE_KEY_6 = 54,
    OCTAVE_KEY_7 = 55,
    OCTAVE_KEY_8 = 56,
    OCTAVE_KEY_9 = 57,

    OCTAVE_KEY_A = 65,
    OCTAVE_KEY_B = 66,
    OCTAVE_KEY_C = 67,
    OCTAVE_KEY_D = 68,
    OCTAVE_KEY_E = 69,
    OCTAVE_KEY_F = 70,
    OCTAVE_KEY_G = 71,
    OCTAVE_KEY_H = 72,
    OCTAVE_KEY_I = 73,
    OCTAVE_KEY_J = 74,
    OCTAVE_KEY_K = 75,
    OCTAVE_KEY_L = 76,
    OCTAVE_KEY_M = 77,
    OCTAVE_KEY_N = 78,
    OCTAVE_KEY_O = 79,
    OCTAVE_KEY_P = 80,
    OCTAVE_KEY_Q = 81,
    OCTAVE_KEY_R = 82,
    OCTAVE_KEY_S = 83,
    OCTAVE_KEY_T = 84,
    OCTAVE_KEY_U = 85,
    OCTAVE_KEY_V = 86,
    OCTAVE_KEY_W = 87,
    OCTAVE_KEY_X = 88,
    OCTAVE_KEY_Y = 89,
    OCTAVE_KEY_Z = 90,

    OCTAVE_KEY_SPACE = 32,
    OCTAVE_KEY_ENTER = 13,
    OCTAVE_KEY_BACKSPACE = 8,
    OCTAVE_KEY_TAB = 9,

    OCTAVE_KEY_SHIFT_L = 16,
    OCTAVE_KEY_CONTROL_L = 17,
    OCTAVE_KEY_ALT_L = 255,
    OCTAVE_KEY_SHIFT_R = 16,
    OCTAVE_KEY_CONTROL_R = 17,
    OCTAVE_KEY_ALT_R = 255,

    OCTAVE_KEY_INSERT = 255,
    OCTAVE_KEY_DELETE = 255,
    OCTAVE_KEY_HOME = 255,
    OCTAVE_KEY_END = 255,
    OCTAVE_KEY_PAGE_UP = 33,
    OCTAVE_KEY_PAGE_DOWN = 34,

    OCTAVE_KEY_UP = 38,
    OCTAVE_KEY_DOWN = 40,
    OCTAVE_KEY_LEFT = 37,
    OCTAVE_KEY_RIGHT = 39,

    OCTAVE_KEY_NUMPAD0 = 96,
    OCTAVE_KEY_NUMPAD1 = 97,
    OCTAVE_KEY_NUMPAD2 = 98,
    OCTAVE_KEY_NUMPAD3 = 99,
    OCTAVE_KEY_NUMPAD4 = 100,
    OCTAVE_KEY_NUMPAD5 = 101,
    OCTAVE_KEY_NUMPAD6 = 102,
    OCTAVE_KEY_NUMPAD7 = 103,
    OCTAVE_KEY_NUMPAD8 = 104,
    OCTAVE_KEY_NUMPAD9 = 105,

    OCTAVE_KEY_F1 = 112,
    OCTAVE_KEY_F2 = 113,
    OCTAVE_KEY_F3 = 114,
    OCTAVE_KEY_F4 = 115,
    OCTAVE_KEY_F5 = 116,
    OCTAVE_KEY_F6 = 117,
    OCTAVE_KEY_F7 = 118,
    OCTAVE_KEY_F8 = 119,
    OCTAVE_KEY_F9 = 120,
    OCTAVE_KEY_F10 = 121,
    OCTAVE_KEY_F11 = 122,
    OCTAVE_KEY_F12 = 123,

    OCTAVE_KEY_PERIOD = 0xBE,
    OCTAVE_KEY_COMMA = 0xBC,
    OCTAVE_KEY_PLUS = 0xBB,
    OCTAVE_KEY_MINUS = 0xBD,

    OCTAVE_KEY_COLON = 0xBA,
    OCTAVE_KEY_QUESTION = 0xBF,
    OCTAVE_KEY_SQUIGGLE = 0xC0,
    OCTAVE_KEY_LEFT_BRACKET = 0xDB,
    OCTAVE_KEY_BACK_SLASH = 0xDC,
    OCTAVE_KEY_RIGHT_BRACKET = 0xDD,
    OCTAVE_KEY_QUOTE = 0xDE,

    OCTAVE_KEY_DECIMAL = 0x6E
};

#endif