#pragma once

#define INPUT_MAX_KEYS 256
#define INPUT_MAX_TOUCHES 4
#define INPUT_MAX_GAMEPADS 4

#if PLATFORM_WINDOWS
#define INPUT_KEYBOARD_SUPPORT 1
#define INPUT_MOUSE_SUPPORT 1
#define INPUT_TOUCH_SUPPORT 1
#define INPUT_GAMEPAD_SUPPORT 1
#elif PLATFORM_LINUX
#define INPUT_KEYBOARD_SUPPORT 1
#define INPUT_MOUSE_SUPPORT 1
#define INPUT_TOUCH_SUPPORT 1
#define INPUT_GAMEPAD_SUPPORT 1
#elif PLATFORM_GAMECUBE
#define INPUT_KEYBOARD_SUPPORT 0
#define INPUT_MOUSE_SUPPORT 0
#define INPUT_TOUCH_SUPPORT 0
#define INPUT_GAMEPAD_SUPPORT 1
#elif PLATFORM_WII
#define INPUT_KEYBOARD_SUPPORT 0
#define INPUT_MOUSE_SUPPORT 1
#define INPUT_TOUCH_SUPPORT 1 // Each wiimote IR treated as a separate pointer 
#define INPUT_GAMEPAD_SUPPORT 1
#elif PLATFORM_3DS
#define INPUT_KEYBOARD_SUPPORT 0
#define INPUT_MOUSE_SUPPORT 0
#define INPUT_TOUCH_SUPPORT 1
#define INPUT_GAMEPAD_SUPPORT 1
#elif PLATFORM_ANDROID
#define INPUT_KEYBOARD_SUPPORT 1
#define INPUT_MOUSE_SUPPORT 1
#define INPUT_TOUCH_SUPPORT 1
#define INPUT_GAMEPAD_SUPPORT 1
#endif