#if EDITOR

#include "CssGenerator.h"
#include "Preferences/Appearance/Theme/CssThemeParser.h"

#include <sstream>
#include <cmath>
#include <unordered_map>
#include <vector>
#include <string>

// ---- Helpers ----

static std::string FormatColor(const ImVec4& c)
{
    int r = (int)std::round(c.x * 255.0f);
    int g = (int)std::round(c.y * 255.0f);
    int b = (int)std::round(c.z * 255.0f);

    if (r < 0) r = 0; if (r > 255) r = 255;
    if (g < 0) g = 0; if (g > 255) g = 255;
    if (b < 0) b = 0; if (b > 255) b = 255;

    if (std::abs(c.w - 1.0f) < 0.001f)
    {
        char buf[16];
        snprintf(buf, sizeof(buf), "#%02X%02X%02X", r, g, b);
        return buf;
    }
    else
    {
        char buf[48];
        snprintf(buf, sizeof(buf), "rgba(%d, %d, %d, %.2f)", r, g, b, c.w);
        return buf;
    }
}

static std::string FormatPx(float v)
{
    char buf[32];
    if (v == std::floor(v))
        snprintf(buf, sizeof(buf), "%dpx", (int)v);
    else
        snprintf(buf, sizeof(buf), "%.1fpx", v);
    return buf;
}

static std::string FormatVec2Px(const ImVec2& v)
{
    return FormatPx(v.x) + " " + FormatPx(v.y);
}

static std::string FormatFloat(float v)
{
    char buf[32];
    snprintf(buf, sizeof(buf), "%.2f", v);
    return buf;
}

static bool Vec4Equal(const ImVec4& a, const ImVec4& b)
{
    return std::abs(a.x - b.x) < 0.0001f &&
           std::abs(a.y - b.y) < 0.0001f &&
           std::abs(a.z - b.z) < 0.0001f &&
           std::abs(a.w - b.w) < 0.0001f;
}

static bool Vec2Equal(const ImVec2& a, const ImVec2& b)
{
    return std::abs(a.x - b.x) < 0.0001f && std::abs(a.y - b.y) < 0.0001f;
}

static bool FloatEqual(float a, float b)
{
    return std::abs(a - b) < 0.0001f;
}

namespace CssGenerator
{

std::string GenerateCss(
    const ImGuiStyle& style,
    bool hasDockTabTextColor,
    const ImVec4& dockTabTextColor,
    const CssThemeData* panelOverrides)
{
    std::ostringstream out;
    out << "/* Generated by Octave Theme Editor */\n\n";

    // --- Style block (non-color properties) ---
    ImGuiStyle defaults;
    std::ostringstream styleBlock;

    if (!FloatEqual(style.Alpha, defaults.Alpha))
        styleBlock << "    alpha: " << FormatFloat(style.Alpha) << ";\n";
    if (!FloatEqual(style.DisabledAlpha, defaults.DisabledAlpha))
        styleBlock << "    disabled-alpha: " << FormatFloat(style.DisabledAlpha) << ";\n";
    if (!Vec2Equal(style.WindowPadding, defaults.WindowPadding))
        styleBlock << "    window-padding: " << FormatVec2Px(style.WindowPadding) << ";\n";
    if (!FloatEqual(style.WindowRounding, defaults.WindowRounding))
        styleBlock << "    window-rounding: " << FormatPx(style.WindowRounding) << ";\n";
    if (!FloatEqual(style.WindowBorderSize, defaults.WindowBorderSize))
        styleBlock << "    window-border-size: " << FormatPx(style.WindowBorderSize) << ";\n";
    if (!Vec2Equal(style.WindowMinSize, defaults.WindowMinSize))
        styleBlock << "    window-min-size: " << FormatVec2Px(style.WindowMinSize) << ";\n";
    if (!Vec2Equal(style.WindowTitleAlign, defaults.WindowTitleAlign))
        styleBlock << "    window-title-align: " << FormatVec2Px(style.WindowTitleAlign) << ";\n";
    if (!FloatEqual(style.ChildRounding, defaults.ChildRounding))
        styleBlock << "    child-rounding: " << FormatPx(style.ChildRounding) << ";\n";
    if (!FloatEqual(style.ChildBorderSize, defaults.ChildBorderSize))
        styleBlock << "    child-border-size: " << FormatPx(style.ChildBorderSize) << ";\n";
    if (!FloatEqual(style.PopupRounding, defaults.PopupRounding))
        styleBlock << "    popup-rounding: " << FormatPx(style.PopupRounding) << ";\n";
    if (!FloatEqual(style.PopupBorderSize, defaults.PopupBorderSize))
        styleBlock << "    popup-border-size: " << FormatPx(style.PopupBorderSize) << ";\n";
    if (!Vec2Equal(style.FramePadding, defaults.FramePadding))
        styleBlock << "    frame-padding: " << FormatVec2Px(style.FramePadding) << ";\n";
    if (!FloatEqual(style.FrameRounding, defaults.FrameRounding))
        styleBlock << "    frame-rounding: " << FormatPx(style.FrameRounding) << ";\n";
    if (!FloatEqual(style.FrameBorderSize, defaults.FrameBorderSize))
        styleBlock << "    frame-border-size: " << FormatPx(style.FrameBorderSize) << ";\n";
    if (!Vec2Equal(style.ItemSpacing, defaults.ItemSpacing))
        styleBlock << "    item-spacing: " << FormatVec2Px(style.ItemSpacing) << ";\n";
    if (!Vec2Equal(style.ItemInnerSpacing, defaults.ItemInnerSpacing))
        styleBlock << "    item-inner-spacing: " << FormatVec2Px(style.ItemInnerSpacing) << ";\n";
    if (!Vec2Equal(style.CellPadding, defaults.CellPadding))
        styleBlock << "    cell-padding: " << FormatVec2Px(style.CellPadding) << ";\n";
    if (!FloatEqual(style.IndentSpacing, defaults.IndentSpacing))
        styleBlock << "    indent-spacing: " << FormatPx(style.IndentSpacing) << ";\n";
    if (!FloatEqual(style.ColumnsMinSpacing, defaults.ColumnsMinSpacing))
        styleBlock << "    columns-min-spacing: " << FormatPx(style.ColumnsMinSpacing) << ";\n";
    if (!FloatEqual(style.ScrollbarSize, defaults.ScrollbarSize))
        styleBlock << "    scrollbar-size: " << FormatPx(style.ScrollbarSize) << ";\n";
    if (!FloatEqual(style.ScrollbarRounding, defaults.ScrollbarRounding))
        styleBlock << "    scrollbar-rounding: " << FormatPx(style.ScrollbarRounding) << ";\n";
    if (!FloatEqual(style.GrabMinSize, defaults.GrabMinSize))
        styleBlock << "    grab-min-size: " << FormatPx(style.GrabMinSize) << ";\n";
    if (!FloatEqual(style.GrabRounding, defaults.GrabRounding))
        styleBlock << "    grab-rounding: " << FormatPx(style.GrabRounding) << ";\n";
    if (!FloatEqual(style.TabRounding, defaults.TabRounding))
        styleBlock << "    tab-rounding: " << FormatPx(style.TabRounding) << ";\n";
    if (!FloatEqual(style.TabBorderSize, defaults.TabBorderSize))
        styleBlock << "    tab-border-size: " << FormatPx(style.TabBorderSize) << ";\n";
    if (!Vec2Equal(style.ButtonTextAlign, defaults.ButtonTextAlign))
        styleBlock << "    button-text-align: " << FormatVec2Px(style.ButtonTextAlign) << ";\n";
    if (!Vec2Equal(style.SelectableTextAlign, defaults.SelectableTextAlign))
        styleBlock << "    selectable-text-align: " << FormatVec2Px(style.SelectableTextAlign) << ";\n";

    std::string styleStr = styleBlock.str();
    if (!styleStr.empty())
    {
        out << "style {\n" << styleStr << "}\n\n";
    }

    // --- Color selectors ---
    // Group colors by selector using the mapping table
    const SelectorMapping* mappings = CssThemeParser::GetSelectorMappings();
    int mappingCount = CssThemeParser::GetSelectorMappingCount();

    // Get Dark theme defaults for comparison
    ImGuiStyle darkDefaults;
    ImGui::StyleColorsDark(&darkDefaults);

    // Build grouped output: selector -> list of "property: color"
    struct SelectorEntry
    {
        std::string selector;
        std::vector<std::string> properties;
    };
    std::vector<SelectorEntry> entries;
    std::unordered_map<std::string, size_t> selectorIndex;

    for (int i = 0; i < mappingCount; ++i)
    {
        int col = mappings[i].imguiCol;
        if (col < 0 || col >= ImGuiCol_COUNT)
            continue;

        if (!Vec4Equal(style.Colors[col], darkDefaults.Colors[col]))
        {
            std::string sel = mappings[i].selector;
            std::string prop = std::string("    ") + mappings[i].property + ": " + FormatColor(style.Colors[col]) + ";";

            auto it = selectorIndex.find(sel);
            if (it == selectorIndex.end())
            {
                selectorIndex[sel] = entries.size();
                entries.push_back({ sel, { prop } });
            }
            else
            {
                entries[it->second].properties.push_back(prop);
            }
        }
    }

    // Dock tab text color (special: tab { color })
    if (hasDockTabTextColor)
    {
        std::string prop = std::string("    color: ") + FormatColor(dockTabTextColor) + ";";
        auto it = selectorIndex.find("tab");
        if (it == selectorIndex.end())
        {
            selectorIndex["tab"] = entries.size();
            entries.push_back({ "tab", { prop } });
        }
        else
        {
            // Insert color as first property in tab block
            entries[it->second].properties.insert(entries[it->second].properties.begin(), prop);
        }
    }

    for (const auto& entry : entries)
    {
        out << entry.selector << " {\n";
        for (const auto& p : entry.properties)
        {
            out << p << "\n";
        }
        out << "}\n\n";
    }

    // --- Panel background overrides ---
    if (panelOverrides)
    {
        if (panelOverrides->hasPanelAssetsBg)
            out << "panel-assets { background: " << FormatColor(panelOverrides->PanelAssetsBg) << "; }\n";
        if (panelOverrides->hasPanelSceneBg)
            out << "panel-scene { background: " << FormatColor(panelOverrides->PanelSceneBg) << "; }\n";
        if (panelOverrides->hasPanelPropertiesBg)
            out << "panel-properties { background: " << FormatColor(panelOverrides->PanelPropertiesBg) << "; }\n";
        if (panelOverrides->hasPanelDebugLogBg)
            out << "panel-debug-log { background: " << FormatColor(panelOverrides->PanelDebugLogBg) << "; }\n";
    }

    return out.str();
}

} // namespace CssGenerator

#endif
