#pragma once

#define TEXT_VERTS_PER_CHAR 6

#if API_VULKAN
#define MAX_FRAMES 2
#define MAX_MESH_VERTEX_COUNT 4294967295
#define SYNC_ON_END_FRAME 1
#define SUPPORTS_SECOND_SCREEN 0
#define MAX_GPU_BONES 64
#endif
