#pragma once

#define BASIC_STATIC_MESH "Static Mesh"
#define BASIC_POINT_LIGHT "Point Light"
#define BASIC_NODE_3D "Node 3D"
#define BASIC_DIRECTIONAL_LIGHT "Directional Light"
#define BASIC_SKELETAL_MESH "Skeletal Mesh"
#define BASIC_BOX "Box"
#define BASIC_SPHERE "Sphere"
#define BASIC_CAPSULE "Capsule"
#define BASIC_PARTICLE "Particle"
#define BASIC_AUDIO "Audio"
#define BASIC_SCENE "Scene"
#define BASIC_CAMERA "Camera"
#define BASIC_TEXT_MESH "Text Mesh"
#define BASIC_INSTANCED_MESH "Instanced Mesh"
