#pragma once

#if EDITOR

#include "EditorIcons.h"

struct SceneIconEntry
{
    const char* mIcon;
    const char* mName;
};

static const SceneIconEntry kSceneIconEntries[] =
{
    { ICON_STREAMLINE_PLUMP_WORLD_REMIX,                           "Default" },
    { ICON_ANT_DESIGN_THUNDERBOLT_FILLED,                          "Thunderbolt" },
    { ICON_ASSETS,                                                 "Assets" },
    { ICON_BASIL_EYE_CLOSED_SOLID,                                 "Eye Closed" },
    { ICON_BEZIER,                                                 "Bezier" },
    { ICON_BITCOIN_ICONS_NODE_2_CONNECTIONS_FILLED,                "Node Connections" },
    { ICON_BI_UNITY,                                               "Unity" },
    { ICON_BLUETOOTH,                                              "Bluetooth" },
    { ICON_BUTTON,                                                 "Button" },
    { ICON_BXS_ARROW_TO_BOTTOM,                                    "Arrow Down" },
    { ICON_BXS_GRID,                                               "Grid" },
    { ICON_BXS_PURCHASE_TAG_ALT,                                   "Tag" },
    { ICON_BXS_TREE,                                               "Tree" },
    { ICON_BX_MATH,                                                "Math" },
    { ICON_BX_MOVE,                                                "Move" },
    { ICON_BX_PACKAGE,                                             "Package" },
    { ICON_CANVAS,                                                 "Canvas" },
    { ICON_CAPSULE,                                                "Capsule" },
    { ICON_CARBON_EDGE_NODE,                                       "Edge Node" },
    { ICON_CBI_DREAMCAST,                                          "Dreamcast" },
    { ICON_CIB_EPIC_GAMES,                                         "Epic Games" },
    { ICON_CIB_NINTENDO_3DS,                                       "Nintendo 3DS" },
    { ICON_CIB_NINTENDO_GAMECUBE,                                  "GameCube" },
    { ICON_CIB_PLAYSTATION3,                                       "PlayStation 3" },
    { ICON_CIB_PLAYSTATION4,                                       "PlayStation 4" },
    { ICON_CIB_WII,                                                "Wii" },
    { ICON_CLAPPERBOARD_CLOSE,                                     "Clapperboard" },
    { ICON_CLAPPERBOARD_OPEN,                                      "Clapperboard Open" },
    { ICON_CLARITY_MOBILE_SOLID,                                   "Mobile" },
    { ICON_CLARITY_NO_ACCESS_SOLID,                                "No Access" },
    { ICON_CONSOLE,                                                "Console" },
    { ICON_CPP,                                                    "C++" },
    { ICON_CS,                                                     "C#" },
    { ICON_CURVEGRAPH,                                             "Curve Graph" },
    { ICON_DASHICONS_ARROW_DOWN,                                   "Arrow Down Alt" },
    { ICON_DASHICONS_ARROW_UP,                                     "Arrow Up" },
    { ICON_DASHICONS_NO_ALT,                                       "No" },
    { ICON_EP_SET_UP,                                              "Set Up" },
    { ICON_EVA_NAVIGATION_2_FILL,                                  "Navigation" },
    { ICON_FA6_SOLID_COMPUTER,                                     "Computer" },
    { ICON_FA_SOLID_MONEY_BILL_WAVE,                               "Money" },
    { ICON_FE_GAMEPAD,                                             "Gamepad" },
    { ICON_FILE_ICONS_GODOT,                                       "Godot" },
    { ICON_FILTER,                                                 "Filter" },
    { ICON_FIREWORK,                                               "Firework" },
    { ICON_FLUENT_BOT_28_FILLED,                                   "Bot" },
    { ICON_FLUENT_KEY_16_FILLED,                                   "Key" },
    { ICON_FLUENT_MDL2_CUBE_SHAPE,                                 "Cube" },
    { ICON_FLUENT_SPARKLE_16_FILLED,                               "Sparkle" },
    { ICON_GLOBE,                                                  "Globe" },
    { ICON_GRIDICONS_CUSTOM_POST_TYPE,                             "Custom Post" },
    { ICON_GROMMET_ICONS_CUBES,                                    "Cubes" },
    { ICON_HIERARCHY,                                              "Hierarchy" },
    { ICON_HUGEICONS_MATERIAL_AND_TEXTURE,                         "Material" },
    { ICON_ICON_PARK_SOLID_INNER_SHADOW_BOTTOM_LEFT,               "Shadow" },
    { ICON_IC_BASELINE_APPLE,                                      "Apple" },
    { ICON_IC_BASELINE_DOWNLOAD,                                   "Download" },
    { ICON_IC_BASELINE_HOURGLASS_BOTTOM,                           "Hourglass" },
    { ICON_IC_BASELINE_LINK,                                       "Link" },
    { ICON_IC_BASELINE_LIST,                                       "List" },
    { ICON_IC_BASELINE_PEOPLE,                                     "People" },
    { ICON_IC_BASELINE_SEARCH,                                     "Search" },
    { ICON_IC_BASELINE_SHARE,                                      "Share" },
    { ICON_IC_BASELINE_STOP,                                       "Stop" },
    { ICON_IC_BASELINE_UPLOAD,                                     "Upload" },
    { ICON_IC_ROUND_COMPUTER,                                      "Computer Alt" },
    { ICON_IC_SHARP_EXTENSION,                                     "Extension" },
    { ICON_IC_SHARP_SETTINGS_BACKUP_RESTORE,                       "Backup Restore" },
    { ICON_IC_TWOTONE_POWER_SETTINGS_NEW,                          "Power" },
    { ICON_INFO,                                                   "Info" },
    { ICON_ION_HAMMER_SHARP,                                       "Hammer" },
    { ICON_IX_CODE,                                                "Code" },
    { ICON_IX_VIDEO_CAMERA_FILLED,                                 "Camera" },
    { ICON_IX_VIDEO_FILE_FILLED,                                   "Video File" },
    { ICON_JSON,                                                   "JSON" },
    { ICON_LAYERS,                                                 "Layers" },
    { ICON_LIGHTBULB,                                              "Lightbulb" },
    { ICON_LINEICONS_VECTOR_NODES_7,                               "Vector Nodes" },
    { ICON_LINE_MD_PAINT_DROP_FILLED,                              "Paint Drop" },
    { ICON_LUA,                                                    "Lua" },
    { ICON_LUCIDE_ROTATE_3D,                                       "Rotate 3D" },
    { ICON_MAGE_SCALE_UP,                                          "Scale" },
    { ICON_MAJESTICONS_MAP_MARKER,                                 "Map Marker" },
    { ICON_MATERIAL_SYMBOLS_ADD,                                   "Add" },
    { ICON_MATERIAL_SYMBOLS_ADD_AD_SHARP,                          "Add Ad" },
    { ICON_MATERIAL_SYMBOLS_ARROW_LEFT,                            "Arrow Left" },
    { ICON_MATERIAL_SYMBOLS_ARROW_RIGHT,                           "Arrow Right" },
    { ICON_MATERIAL_SYMBOLS_AUDIO_FILE_SHARP,                      "Audio File" },
    { ICON_MATERIAL_SYMBOLS_BOMB,                                  "Bomb" },
    { ICON_MATERIAL_SYMBOLS_CHECK,                                 "Check" },
    { ICON_MATERIAL_SYMBOLS_CHECK_CIRCLE,                          "Check Circle" },
    { ICON_MATERIAL_SYMBOLS_CLOUD_OUTLINE,                         "Cloud" },
    { ICON_MATERIAL_SYMBOLS_FILE_COPY_SHARP,                       "File Copy" },
    { ICON_MATERIAL_SYMBOLS_FLAG,                                  "Flag" },
    { ICON_MATERIAL_SYMBOLS_FOLDER_OPEN_SHARP,                     "Folder Open" },
    { ICON_MATERIAL_SYMBOLS_FOLDER_SHARP,                          "Folder" },
    { ICON_MATERIAL_SYMBOLS_LIGHT_FAST_FORWARD,                    "Fast Forward" },
    { ICON_MATERIAL_SYMBOLS_LIGHT_FAST_FORWARD_1,                  "Fast Forward Alt" },
    { ICON_MATERIAL_SYMBOLS_LOCK_OPEN_SHARP,                       "Lock Open" },
    { ICON_MATERIAL_SYMBOLS_LOCK_SHARP,                            "Lock" },
    { ICON_MATERIAL_SYMBOLS_MIC,                                   "Microphone" },
    { ICON_MATERIAL_SYMBOLS_NOTE_ADD_SHARP,                        "Note Add" },
    { ICON_MATERIAL_SYMBOLS_PAUSE,                                 "Pause" },
    { ICON_MATERIAL_SYMBOLS_PERSON,                                "Person" },
    { ICON_MATERIAL_SYMBOLS_POWER_SETTINGS_CIRCLE,                 "Power Circle" },
    { ICON_MATERIAL_SYMBOLS_ROCKET_LAUNCH,                         "Rocket" },
    { ICON_MATERIAL_SYMBOLS_SAVE_SHARP,                            "Save" },
    { ICON_MATERIAL_SYMBOLS_SETTINGS,                              "Settings" },
    { ICON_MATERIAL_SYMBOLS_STAR,                                  "Star" },
    { ICON_MATERIAL_SYMBOLS_TARGET,                                "Target" },
    { ICON_MATERIAL_SYMBOLS_TV_OUTLINE_ROUNDED,                    "TV" },
    { ICON_MATERIAL_SYMBOLS_VIEW_TIMELINE_SHARP,                   "Timeline" },
    { ICON_MATERIAL_SYMBOLS_WARNING,                               "Warning" },
    { ICON_MATERIAL_SYMBOLS_WIDGET_MEDIUM,                         "Widget" },
    { ICON_MDI_AWS,                                                "AWS" },
    { ICON_MDI_AXIS_ARROW,                                         "Axis Arrow" },
    { ICON_MDI_BUG,                                                "Bug" },
    { ICON_MDI_CART,                                               "Cart" },
    { ICON_MDI_CONTENT_PASTE,                                      "Paste" },
    { ICON_MDI_DOLPHIN,                                            "Dolphin" },
    { ICON_MDI_EYE,                                                "Eye" },
    { ICON_MDI_GIFT,                                               "Gift" },
    { ICON_MDI_LINUX,                                              "Linux" },
    { ICON_MDI_MAGIC,                                              "Magic" },
    { ICON_MDI_MIXER_SETTINGS_VERTICAL,                            "Mixer" },
    { ICON_MDI_NINTENDO_WIIU,                                      "Wii U" },
    { ICON_MDI_PEOPLE_ADD,                                         "People Add" },
    { ICON_MDI_PLAY,                                               "Play" },
    { ICON_MDI_RESISTOR_NODES,                                     "Resistor Nodes" },
    { ICON_MDI_SERVER_OUTLINE,                                     "Server" },
    { ICON_MDI_STEAM,                                              "Steam" },
    { ICON_MDI_TARGET,                                             "Target Alt" },
    { ICON_MDI_THUMBS_DOWN,                                        "Thumbs Down" },
    { ICON_MDI_THUMBS_UP,                                          "Thumbs Up" },
    { ICON_MDI_WEBCAM,                                             "Webcam" },
    { ICON_MINGCUTE_PAPER_FILL,                                    "Paper" },
    { ICON_PH_CURSOR_TEXT_LIGHT,                                   "Cursor Text" },
    { ICON_PH_MAGNET_FILL,                                         "Magnet" },
    { ICON_PH_MUSIC_NOTE_FILL,                                     "Music Note" },
    { ICON_PH_PAPER_PLANE_TILT_FILL,                               "Paper Plane" },
    { ICON_PH_SPHERE,                                              "Sphere" },
    { ICON_POLYGON,                                                "Polygon" },
    { ICON_QLEMENTINE_ICONS_WAVE_16,                               "Wave" },
    { ICON_RAPHAEL_NO,                                             "No Alt" },
    { ICON_RECT,                                                   "Rectangle" },
    { ICON_RIVET_ICONS_AUDIO_SOLID,                                "Audio" },
    { ICON_RI_CURSOR_FILL,                                         "Cursor" },
    { ICON_RI_FIGMA_LINE,                                          "Figma" },
    { ICON_RI_NETWORK_FILL,                                        "Network" },
    { ICON_RI_PLAYSTATION_FILL,                                    "PlayStation" },
    { ICON_RI_SWITCH_FILL,                                         "Switch" },
    { ICON_RI_WINDOWS_FILL,                                        "Windows" },
    { ICON_SAVEAS,                                                 "Save As" },
    { ICON_SCENE,                                                  "Scene" },
    { ICON_SHADOW,                                                 "Shadow Alt" },
    { ICON_SIMPLE_ICONS_PLAYSTATION2,                              "PlayStation 2" },
    { ICON_SIMPLE_ICONS_PLAYSTATION5,                              "PlayStation 5" },
    { ICON_SIMPLE_ICONS_PLAYSTATIONPORTABLE,                       "PSP" },
    { ICON_SIMPLE_ICONS_PLAYSTATIONVITA,                           "PS Vita" },
    { ICON_SKELETON,                                               "Skeleton" },
    { ICON_SPLINE,                                                 "Spline" },
    { ICON_STREAMLINE_LOGOS_UNREAL_ENGINE_LOGO_SOLID,              "Unreal" },
    { ICON_STREAMLINE_LOG_SOLID,                                   "Log" },
    { ICON_STREAMLINE_SHARP_GAMEBOY_SOLID,                         "Gameboy" },
    { ICON_STREAMLINE_SHARP_NEW_FILE_REMIX,                        "New File" },
    { ICON_STREAMLINE_SHARP_WAVE_SIGNAL_REMIX,                     "Wave Signal" },
    { ICON_STREAMLINE_ULTIMATE_NAVIGATION_MENU_HORIZONTAL_1_BOLD,  "Menu" },
    { ICON_SUN,                                                    "Sun" },
    { ICON_TABLER_CHAIR_DIRECTOR,                                  "Director Chair" },
    { ICON_TABLER_HAND_GRAB,                                       "Hand Grab" },
    { ICON_TDESIGN_IMAGE_FILLED,                                   "Image" },
    { ICON_TDESIGN_NOTIFICATION_FILLED,                            "Notification" },
    { ICON_TDESIGN_TABLE_FILLED,                                   "Table" },
    { ICON_TEENYICONS_N64_SOLID,                                   "N64" },
    { ICON_TEXTMESH,                                               "Text Mesh" },
    { ICON_TEXTWIDGET,                                             "Text Widget" },
    { ICON_TORUS,                                                  "Torus" },
    { ICON_UIL_ANDROID,                                            "Android" },
    { ICON_UIWIDGET,                                               "UI Widget" },
    { ICON_UNDO,                                                   "Undo" },
    { ICON_VIEWPORT3D,                                             "Viewport 3D" },
    { ICON_WIFI,                                                   "WiFi" },
    { ICON_ZONDICONS_EXCLAMATION_SOLID,                            "Exclamation" },
    { ICON_ZONDICONS_TRASH,                                        "Trash" },
};

static constexpr int32_t kSceneIconCount = sizeof(kSceneIconEntries) / sizeof(kSceneIconEntries[0]);

inline const char* GetSceneIconByIndex(uint8_t index)
{
    if (index < kSceneIconCount)
        return kSceneIconEntries[index].mIcon;
    return nullptr;
}

#endif
